### ISSUE TITLE
Use Qwen2-VL as backbone

### ISSUE THREAD

**Issue by VoVAllen** [TIGER-AI-Lab/VLM2Vec#1]
Qwen2-VL showed much better performance on multiple tasks. Will VLM2Vec try it?

**Comment by XMHZZ2018** [comment]
@VoVAllen 
Thanks for pointing that out! Using Qwen2-VL as the backbone is definitely one of the most important updates planned for VLM2Vec. Other potential ways to further improve the model include mining more hard negatives during training, incorporating more diverse training data, or integrating pure text-based tasks. We may release an improved version of VLM2Vec in the future.
