### ISSUE TITLE
Code does not support the training of Llama-3.2-Vision

### ISSUE THREAD

**Issue by haon-chen** [TIGER-AI-Lab/VLM2Vec#10]
Your current code does not support the training of  Llama-3.2-Vision-11B, which is the SOTA open-source VLM. Could you modity your data collator and model to support the training of this VLM?

**Comment by XMHZZ2018** [comment]
Thank you for your interest in our work! We are currently working on supporting more VLMs and will be adding Llama-3.2-Vision-11B soon.
