### ISSUE TITLE
Why use Precision@1 instead of Recall@K as a metric?

### ISSUE THREAD

**Issue by saicoco** [TIGER-AI-Lab/VLM2Vec#14]
I want to compare the performance differences between VLM-vec, MM-Embed, and UniIR on retrieval task.
 
I just find that data for the retrieval task is the same in both MM-Embed and M-BEIR

**Comment by XMHZZ2018** [comment]
@saicoco
 
Thank you for your interest! Yes, our current framework uses Precision@1 as a metric. We are actively working on adding additional metrics, including Recall and ranking-based metrics such as NDCG and MRR.
