### ISSUE TITLE
training with Phi-V-3.5 raise Error

### ISSUE THREAD

**Issue by PeterAdam2015** [TIGER-AI-Lab/VLM2Vec#15]
Thank you for your opening-source and I'am highly approcicate your MMEB benchmark and this amazing trainging framework ! 🎆 👍 I believe is really necessary for multi-modal embedding community ! 🥳 
I cloned your code and run your scripts/run_train_phi_3.5_v.sh script,  But get the following TypeError
<img width="973" alt="截屏2024-12-02 19 04 49" src="https://github.com/user-attachments/assets/d08aa479-c40e-4a95-b742-e749489af9d1">

It seemd that the in a mini batch-data, collector get in-consistent batch data —— both real image and dummy image, which can't be handled by phi3-v
https://huggingface.co/microsoft/Phi-3.5-vision-instruct/blob/main/modeling_phi3_v.py#L240

<img width="971" alt="image" src="https://github.com/user-attachments/assets/c4fe9ed9-0a24-4f61-b4cb-bd5dd1af6339">

Thanks, and waitting for your reply!

**Comment by XMHZZ2018** [comment]
@PeterAdam2015

Thank you for your interest in our work and for pointing out this issue! I believe this was an error we accidentally introduced while incorporating some other features. I will fix it today.

**Comment by XMHZZ2018** [comment]
@PeterAdam2015 

I have fixed this issue. Please let me know whether it works. Thanks!

**Comment by PeterAdam2015** [comment]
Well, I've tried run the same training script, it works ! Thanks 😄

**Comment by XMHZZ2018** [comment]
Great! Thanks for confirming!
