### ISSUE TITLE
Finetuning with limited computational resources

### ISSUE THREAD

**Issue by PixarHero** [TIGER-AI-Lab/VLM2Vec#16]
Thank you for your inspired and excellent work! I would like to inquire about fine-tuning with limited computational resources. Specifically, I have access to 2 A100 GPUs with 80GB of memory each. Given these constraints, I would like to know if fine-tuning is feasible and if you have any advice for optimizing the process.

**Comment by XMHZZ2018** [comment]
@PixarHero 

Thank you for your interest in our work! With 2 A100 GPUs, fine-tuning is technically feasible but requires more training time. You can reduce the batch size, image resolution, and training data size accordingly to strike a balance between performance and training time.

**Comment by PixarHero** [comment]
Thanks a lot for your advice, I will try it! Excellent work!
