### ISSUE TITLE
pooling bug when using llava and left padding

### ISSUE THREAD

**Issue by zhengbw0324** [TIGER-AI-Lab/VLM2Vec#18]
When using llava as the backbone and using left padding, the pooling operation should directly take the hidden_states with index -1 instead of calculating the sequence length based on the attention mask.

https://github.com/TIGER-AI-Lab/VLM2Vec/blob/086bdc6a18e075bcc9c45af62245f07397878f3c/src/model.py#L39-L49

**Comment by XMHZZ2018** [comment]
Hi @zhengbw0324 ,

Thank you for pointing this out! You're right—the line about setting the tokenizer's padding side is a bit confusing, so I will remove it.

For clarification, VLM2Vec-LLava-next still uses right padding, and the get_batch_input function can be found here:
https://github.com/TIGER-AI-Lab/VLM2Vec/blob/main/src/collator.py#L26. So the pooling function could work as it is.

**Comment by zhengbw0324** [comment]
@XMHZZ2018 
Thanks for clarifying my confusion.
