### ISSUE TITLE
Whether TIGER-Lab/VLM2Vec-LLaVa-Next has been integrated with LoRA weights?

### ISSUE THREAD

**Issue by zhengbw0324** [TIGER-AI-Lab/VLM2Vec#19]
In your model card, [TIGER-Lab/VLM2Vec-LLaVa-Next](https://huggingface.co/TIGER-Lab/VLM2Vec-LLaVa-Next) is fine-tuned based on LoRA, but the open source weights are the full weights rather than the adapter weights. Have the adapter weights been integrated?

**Comment by XMHZZ2018** [comment]
@zhengbw0324 
Yes, the model was trained using LoRA. I have merged the adapter weights with the full model weights to make it more convenient for people to use.
