### ISSUE TITLE
The results are better than those in the paper

### ISSUE THREAD

**Issue by B-201** [TIGER-AI-Lab/VLM2Vec#2]
I tested some of the datasets in the eval set and found that the results are higher than those in the paper. Is there an update to the LoRA model compared to what was presented in the paper?

**Comment by wenhuchen** [comment]
I think some fluctuations is reasonable. We do have some update checkpoints coming soon trained with large batch size.

**Comment by khazic** [comment]
I’m curious why the index of full train is not as good as lora?

**Comment by wenhuchen** [comment]
We don't know either. One hypothesis is that the full finetune will overfit to training set more easily.

**Comment by zihaolucky** [comment]
Hi @wenhuchen how many nodes/gpus need to train the model with bs=1024?  Does GradCache help?

**Comment by XMHZZ2018** [comment]
Hi @zihaolucky ,
We used 8 H100 GPUs. GradCache is necessary to increase the batch size.
