### ISSUE TITLE
The dataset is missing images

### ISSUE THREAD

**Issue by WGowi** [TIGER-AI-Lab/VLM2Vec#9]
When I searched for dataset images on huggingface, I found that the dataset only provided the image path but not the image itself.
<img width="1914" alt="image" src="https://github.com/user-attachments/assets/6bea5a9e-c35e-46d7-ae4f-1f471dd068ae">

**Comment by XMHZZ2018** [comment]
<img width="1264" alt="Screenshot 2024-11-22 at 3 18 02 PM" src="https://github.com/user-attachments/assets/6c81d447-668e-4251-a949-533ea1c29fb8">

@WGowi 
Hi, the images are also provided in our HF repo. Please check the above screenshot.
